name: Test AI Review on PR diff
run-name: Test AI Review on PR diff (PR ${{ inputs.pr_number }})

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: number
      user_id:
        required: true
        type: string
        default: korosuke613

jobs:
  test-ai-review:
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/reusable-ai-review.yaml
    secrets: inherit
    with:
      pr_number: ${{ inputs.pr_number }}
      user_id: ${{ inputs.user_id }}
      environment: "test-ai-review"
